<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CacheVault.Core\CacheVault.Core.csproj" />
    <ProjectReference Include="..\CacheVault.Persistence\CacheVault.Persistence.csproj" />
    <ProjectReference Include="..\CacheVault.Protocol\CacheVault.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Acknowledgements\" />
    <Folder Include="Synchronization\" />
    <Folder Include="Replica\" />
  </ItemGroup>

</Project>
